name: CI Pipeline

on: 
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install Deps
        run: yarn
      # - name: Run tests
      #   run: yarn test
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build